{% set repo = environ.get('GIT_REPO',"MPAS-dev") %}

package:
    name: mpas_analysis
    version: {{ GIT_DESCRIBE_TAG }}

source:
    git_rev: {{ environ.get('GIT_REVISION', 'master') }}
    git_url: git://github.com/{{ GIT_REPO }}/MPAS-Analysis

build:
    number: 0

test:
    imports:
        - mpas_analysis

requirements:
    build:
        - python <3
        - setuptools
    run:
        - python <3
        - numpy
        - scipy
        - matplotlib
        - netcdf4 1.2.9
        - xarray 0.9.6
        - dask 0.15.2
        - bottleneck 1.2.1
        - basemap
        - lxml  3.8.0
        - nco 4.6.8

about:
    home:  http://gitub.com/UV-CDAT/uvcdat



